CREATE TABLE `erp_vendi_bil` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增编码',
  `erp_inquiry_bil_id` bigint(20) DEFAULT NULL COMMENT '来源单编码 从询价单转入的由触发器自动填入，否则为空',
  `customerId` bigint(20) NOT NULL COMMENT '客户 从询价单转入的由触发器自动填入，否则新增时用户界面选择',
  `isCheck` tinyint(4) DEFAULT '-1' COMMENT '是否提交审核。-1：可以更改；0：提交待审，客服不能更改 1：审核通过，不能更改',
  `isSubmit` tinyint(4) DEFAULT '-1' COMMENT '是否提交出仓 -1：不可出仓；0：可出仓 1：已出仓',
  `isCost` tinyint(4) DEFAULT '0' COMMENT '支付状态  0：未支付，1：已支付',
  `erp_payment_type_id` int(11) DEFAULT NULL COMMENT '支付方式ID',
  `creatorId` bigint(20) NOT NULL COMMENT '登录账户ID 初建人编码；--@CreatorId',
  `empId` bigint(20) DEFAULT NULL COMMENT '初建员工ID；--@ 公司的客服 erc$staff_id',
  `checkUserId` bigint(20) DEFAULT NULL COMMENT '审核用户登录ID',
  `checkEmpId` bigint(20) DEFAULT NULL COMMENT '审核员工ID',
  `empName` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '员工姓名。如果是询价单转，是执行checked的员工，否则是直接新增的员工',
  `checkEmpName` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '审核员工姓名',
  `zoneNum` varchar(30) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '客户所在地区的区号 触发器获取',
  `code` varchar(100) CHARACTER SET utf8mb4 NOT NULL COMMENT '单号 新增时触发器生成',
  `inquiryCode` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '询价单号，冗余',
  `priceSumSell` decimal(20,4) DEFAULT NULL COMMENT '售价金额总计',
  `createdDate` datetime DEFAULT NULL COMMENT '初建时间；--@CreatedDate',
  `createdBy` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '登录账户名称  初建人员；--@CreatedBy',
  `costConfirmTime` datetime DEFAULT NULL COMMENT '出纳收款确认时间，点击确认按钮生成',
  `costTime` datetime DEFAULT NULL COMMENT '客户提供交费时间，客服填写',
  `stockTime` datetime DEFAULT NULL COMMENT '备货时间，非空时已备货',
  `stockUserId` bigint(20) DEFAULT NULL COMMENT '备货用户ID',
  `stockEmpId` bigint(20) DEFAULT NULL,
  `stockEmpName` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '备货员工姓名',
  `outTime` datetime DEFAULT NULL COMMENT '出仓时间 非空时已出仓可发货',
  `outUserId` bigint(20) DEFAULT NULL COMMENT '出仓人 ',
  `outEmpId` bigint(20) DEFAULT NULL COMMENT '初建员工ID；--@ 公司的客服 erc$staff_id',
  `outEmpName` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '员工姓名。如果是询价单转，是执行checked的员工，否则是直接新增的员工',
  `lastModifiedDate` datetime DEFAULT NULL COMMENT '最新时间；--@LastModifiedDate',
  `lastModifiedId` bigint(20) DEFAULT NULL COMMENT '最新修改人编码；正常是审核人 触发器维护 --',
  `lastModifiedEmpId` bigint(20) DEFAULT NULL COMMENT '最新修改人员工ID；触发器维护 erc$staff_id',
  `lastModifiedEmpName` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '最新修改员工姓名',
  `lastModifiedBy` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '最新人员；--@LastModifiedBy',
  `needTime` datetime DEFAULT NULL COMMENT '期限时间  客户要求什么时间到货',
  `erc$telgeo_contact_id` bigint(20) DEFAULT NULL COMMENT '客户收货地址，erc_customer_address.id',
  `takeGeoTel` varchar(1000) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '提货地址和电话；--这里用文本不用ID，防止本单据流程中地址被修改了',
  `memo` varchar(2000) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '备注',
  `customerDemand` varchar(2000) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '客户需求',
  PRIMARY KEY (`id`),
  UNIQUE KEY `erp_vendi_bil_code_idx` (`code`) USING BTREE,
  KEY `erp_vendi_bil_erp_inquiry_bil_id_idx` (`erp_inquiry_bil_id`),
  KEY `erp_vendi_bil_creatorId_idx` (`creatorId`),
  KEY `erp_vendi_bil_lastModifiedId_idx` (`lastModifiedId`),
  KEY `erp_vendi_bil_createdDate_idx` (`createdDate`),
  KEY `erp_vendi_bil_payment_type_id_idx` (`erp_payment_type_id`) USING BTREE,
  KEY `erp_vendi_bil_inquiryCode_idx` (`inquiryCode`) USING BTREE,
  CONSTRAINT `fk_erp_vendi_bil_erp_inquiry_bil_id` FOREIGN KEY (`erp_inquiry_bil_id`) REFERENCES `erp_inquiry_bil` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_erp_vendi_bil_erp_payment_type_id` FOREIGN KEY (`erp_payment_type_id`) REFERENCES `erp_payment_type` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='销售订单主表＃--sn=TB04001&type=mdsMaster&jname=VenditionBill&title=销售订单&finds={"createdDate":1,"lastModifiedDate":1}';
